basdat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

import register_user.urls as register_user
import login.urls as login
import register_organisasi.urls as register_organisasi

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^daftar/', include(register_user, namespace='daftar')),
    url(r'^masuk/', include(login, namespace='masuk')),
    url(r'^register-organisasi/', include(register_organisasi, namespace='register-organisasi')),
    url(r'^', RedirectView.as_view(url='/masuk/', permanent='true'), name='index')
]

login/urls.py
from django.conf.urls import url
from .views import index, login

urlpatterns = [
    url(r"^", index, name="index"),
    url(r"^submit/", login, name="submit")
]

register_organisasi/urls.py
from django.conf.urls import url

from .views import index, submit_form

urlpatters = [
    url(r'^', index, name='index'),
    url(r'^submit', submit_form, name='submit')
]

register_organisasi/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Berita(models.Model):
    kode_unik = models.CharField(primary_key=True, max_length=50)
    kegiatan = models.ForeignKey('Kegiatan', models.CASCADE, db_column='kegiatan')
    judul = models.CharField(max_length=100)
    deskripsi = models.TextField()
    tgl_update = models.DateField()
    tgl_kegiatan = models.DateField()

    class Meta:
        managed = False
        db_table = 'berita'


class Donatur(models.Model):
    email = models.ForeignKey('User', models.CASCADE, db_column='email', primary_key=True)
    saldo = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'donatur'


class DonaturKegiatan(models.Model):
    donatur = models.ForeignKey(Donatur, models.CASCADE, db_column='donatur', primary_key=True)
    kegiatan = models.ForeignKey('Kegiatan', models.CASCADE, db_column='kegiatan')
    tanggal = models.DateField()
    nominal = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'donatur_kegiatan'
        unique_together = (('donatur', 'kegiatan'),)


class DonaturOrganisasi(models.Model):
    donatur = models.ForeignKey(Donatur, models.CASCADE, db_column='donatur', primary_key=True)
    organisasi = models.ForeignKey('OrganisasiTerverifikasi', models.CASCADE, db_column='organisasi')
    tanggal = models.DateField()
    nominal = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'donatur_organisasi'
        unique_together = (('donatur', 'organisasi'),)


class Kategori(models.Model):
    kode = models.CharField(primary_key=True, max_length=20)
    nama = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'kategori'


class KategoriKegiatan(models.Model):
    kode_kegiatan = models.ForeignKey('Kegiatan', models.CASCADE, db_column='kode_kegiatan', primary_key=True)
    kode_kategori = models.ForeignKey(Kategori, models.CASCADE, db_column='kode_kategori')

    class Meta:
        managed = False
        db_table = 'kategori_kegiatan'
        unique_together = (('kode_kegiatan', 'kode_kategori'),)


class KeahlianRelawan(models.Model):
    email = models.ForeignKey('Relawan', models.CASCADE, db_column='email', primary_key=True)
    keahlian = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'keahlian_relawan'
        unique_together = (('email', 'keahlian'),)


class Kegiatan(models.Model):
    kode_unik = models.CharField(primary_key=True, max_length=20)
    organisasi_perancang = models.ForeignKey('OrganisasiTerverifikasi', models.CASCADE, db_column='organisasi_perancang')
    judul = models.CharField(max_length=50)
    dana_dibutuhkan = models.IntegerField()
    tanggal_mulai = models.DateField()
    tanggal_selesai = models.DateField()
    deskripsi = models.TextField()

    class Meta:
        managed = False
        db_table = 'kegiatan'


class LaporanKeuangan(models.Model):
    organisasi = models.ForeignKey('OrganisasiTerverifikasi', models.CASCADE, db_column='organisasi', primary_key=True)
    tgl_dibuat = models.DateField()
    rincian_pemasukan = models.TextField()
    total_pemasukan = models.IntegerField()
    total_pengeluaran = models.IntegerField()
    is_disetujui = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'laporan_keuangan'
        unique_together = (('organisasi', 'tgl_dibuat'),)


class Organisasi(models.Model):
    email_organisasi = models.CharField(primary_key=True, max_length=50)
    website = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    provinsi = models.CharField(max_length=50)
    kabupaten_kota = models.CharField(max_length=50)
    kecamatan = models.CharField(max_length=50)
    kelurahan = models.CharField(max_length=50)
    kode_pos = models.CharField(max_length=50)
    status_verifikasi = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'organisasi'


class OrganisasiTerverifikasi(models.Model):
    email_organisasi = models.ForeignKey(Organisasi, models.CASCADE, db_column='email_organisasi', primary_key=True)
    nomor_registrasi = models.CharField(max_length=50)
    status_aktif = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'organisasi_terverifikasi'


class PengurusOrganisasi(models.Model):
    email = models.ForeignKey('User', models.CASCADE, db_column='email', primary_key=True)
    organisasi = models.ForeignKey(Organisasi, models.CASCADE, db_column='organisasi')

    class Meta:
        managed = False
        db_table = 'pengurus_organisasi'


class PenilaianPerforma(models.Model):
    email_relawan = models.ForeignKey('Relawan', models.CASCADE, db_column='email_relawan', primary_key=True)
    organisasi = models.ForeignKey(OrganisasiTerverifikasi, models.CASCADE, db_column='organisasi')
    id = models.IntegerField()
    deskripsi = models.TextField()
    tgl_penilaian = models.DateField()
    nilai_skala = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'penilaian_performa'
        unique_together = (('email_relawan', 'organisasi', 'id'),)


class Relawan(models.Model):
    email = models.ForeignKey('User', models.CASCADE, db_column='email', primary_key=True)
    no_hp = models.CharField(max_length=20)
    tanggal_lahir = models.DateField()

    class Meta:
        managed = False
        db_table = 'relawan'


class RelawanOrganisasi(models.Model):
    email_relawan = models.ForeignKey(Relawan, models.CASCADE, db_column='email_relawan', primary_key=True)
    organisasi = models.ForeignKey(Organisasi, models.CASCADE, db_column='organisasi')

    class Meta:
        managed = False
        db_table = 'relawan_organisasi'
        unique_together = (('email_relawan', 'organisasi'),)


class Reward(models.Model):
    kode_kegiatan = models.ForeignKey(Kegiatan, models.CASCADE, db_column='kode_kegiatan', primary_key=True)
    barang_reward = models.CharField(max_length=50)
    harga_min = models.IntegerField()
    harga_max = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'reward'
        unique_together = (('kode_kegiatan', 'barang_reward'),)


class Sponsor(models.Model):
    email = models.ForeignKey('User', models.CASCADE, db_column='email', primary_key=True)
    logo_sponsor = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'sponsor'


class SponsorOrganisasi(models.Model):
    sponsor = models.ForeignKey(Sponsor, models.CASCADE, db_column='sponsor', primary_key=True)
    organisasi = models.ForeignKey(OrganisasiTerverifikasi, models.CASCADE, db_column='organisasi')
    tanggal = models.DateField()
    nominal = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'sponsor_organisasi'
        unique_together = (('sponsor', 'organisasi'),)


class TujuanOrganisasi(models.Model):
    organisasi = models.ForeignKey(Organisasi, models.CASCADE, db_column='organisasi', primary_key=True)
    tujuan = models.TextField()

    class Meta:
        managed = False
        db_table = 'tujuan_organisasi'
        unique_together = (('organisasi', 'tujuan'),)


class User(models.Model):
    email = models.CharField(primary_key=True, max_length=50)
    password = models.CharField(max_length=50)
    nama = models.CharField(max_length=100)
    alamat_lengkap = models.TextField()

    class Meta:
        managed = False
        db_table = 'user'

register_organisasi/views.py
from django.shortcuts import render
from __future__ import unicode_literals

from django.db import connection, IntegrityError
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages

from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
    if 'username' in request.session.keys():
        html = 'layout/register-organisasi.html'
        return render(request, html)
    return HttpResponseRedirect(reverse('masuk:index'))

@csrf_exempt
def submit_form(request):
    if request.method == "POST":
        nama_orgns = request.POST['nama-orgns']
        website = request.POST['website']
        email_orgns = request.POST['email-orgns']
        kecamatan_orgns = request.POST['kecamatan-orgns']
        kabupaten_orgns = request.POST['kabupaten-orgns']
        provinsi_orgns = request.POST['provinsi-orgns']
        kode_pos_orgns = request.POST['kode-pos-orgns']
        alamat_orgns = request.POST['alamat-orgns']
        tujuan_orgns = request.POST['tujuan-orgns']
        nama_pengurus = request.POST['pengurus-orgns']
        email_pengurus = request.POST['email-pengurus']
        alamat_pengurus = request.POS['alamat-pengurus']

        try:
            cursor = connection.cursor()
            cursor.execute("SELECT * from organisasi where email_organisasi='"+email_orgns+"'")
            select = cursor.fetchone()
            if(select):
                return HttpResponse("Email sudah terdaftar")
            else:
                cursor.execute("SELECT * from organisasi where nama ='"+nama_orgns+"'")
                select = cursor.fetchone();
                if(select):
                    return HttpResponse("Nama sudah terdaftar")
                else:
                    cursor.execute("INSERT INTO organisasi VALUES(%s, %s, %s, %s,%s, %s, %s, %s, %s)",
                                   [email_orgns, website, nama_orgns, provinsi_orgns, kabupaten_orgns, kecamatan_orgns,
                                    alamat_orgns, kode_pos_orgns, "Aktif"])
                    cursor.execute("INSERT INTO pengurusorganisasi VALUES(%s, %s)", [email_pengurus, nama_orgns])
                    return HttpResponse("HEHEHEHEH")
        except IntegrityError:
            messages.error(request, "HEHEHEH")
    return HttpResponseRedirect(reverse('register-organisasi:index'))

register_organisasi/templates/layout/register-organisasi.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<style>
  body {font-family: Arial, Helvetica, sans-serif;}
  * {box-sizing: border-box}
  /* Full-width input fields */
  input[type=text], input[type=email] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 22px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
  }

  /* Add a background color when the inputs get focus */
  input[type=text]:focus {
    background-color: #ddd;
    outline: none;
  }

  /* Set a style for all buttons */
  button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
  }

  button:hover {
    opacity:1;
  }

  /* Extra styles for the cancel button */
  .cancelbtn {
    padding: 14px 20px;
    background-color: #f44336;
  }

  /* Float cancel and signup buttons and add an equal width */
  .cancelbtn, .signupbtn {
    float: left;
    width: 50%;
  }

  /* Add padding to container elements */
  .container {
    padding: 16px;
  }

  /* The Modal (background) */
  .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: #474e5d;
    padding-top: 50px;
  }

  /* Modal Content/Box */
  .modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
  }

  /* Style the horizontal ruler */
  hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
  }

  /* The Close Button (x) */
  .close {
    position: absolute;
    right: 35px;
    top: 15px;
    font-size: 40px;
    font-weight: bold;
    color: #f1f1f1;
  }

  .close:hover,
  .close:focus {
    color: #f44336;
    cursor: pointer;
  }

  /* Clear floats */
  .clearfix::after {
    content: "";
    clear: both;
    display: table;
  }



  /* Change styles for cancel button and signup button on extra small screens */
  @media screen and (max-width: 300px) {
    .cancelbtn, .signupbtn {
     width: 100%;
   }
 }
</style>

<body>
  <form class="modal-content" action="{% url 'register-organisasi:submit' %}" method="POST">
    <div class="container">
      <h1>Form Pendaftaran Organisasi</h1>
      <p>Isi formulir berikut untuk membuat akun organisasi</p>
      <hr>
      <label for="nama-orgns"><b>Nama Organisasi</b></label>
      <input type="text" placeholder="Nama Organisasi" name="nama-orgns" required>

      <label for="website"><b>Website</b></label>
      <input type="text" placeholder="bingung.com" name="website" required>

      <label for="email-orgns"><b>Email</b></label>
      <input type="email" placeholder="Email" name="email-orgns" required>

      <label for="kecamatan-orgns"><b>Kecamatan</b></label>
      <input type="text" placeholder="Kecamatan" name="kecamatan-orgns" required>

      <label for="Kabupaten-orgns"><b>Kabupaten</b></label>
      <input type="text" placeholder="Kabupaten" name="kabupaten-orgns" required>

      <label for="provinsi-orgns"><b>Provinsi</b></label>
      <input type="text" placeholder="Provinsi" name="provinsi-orgns" required>

      <label for="kode-pos-orgns"><b>Kode Pos</b></label>
      <input type="text" placeholder="Kode Pos" name="kode-pos-orgns" required>

      <label for="alamat-orgns"><b>Alamat</b></label>
      <input type="text" placeholder="Jalan/Desa/Kelurahan/No.Rumah" name="alamat-orgns" required>

      <label for="tujuan-orgns"><b>Tujuan Organisasi</b></label>
      <input type="text" placeholder="Tujuan Organisasi" name="tujuan-orgns" required>

      <label for="pengurus-orgns"><b>Nama Pengurus</b></label>
      <input type="text" placeholder="Nama Pengurus" name="pengurus-orgns" required>

      <label for="email-pengurus"><b>Email Pengurus</b></label>
      <input type="email" placeholder="Email Pengurus" name="email-pengurus" required>

      <label for="alamat-pengurus"><b>Alamat Pengurus</b></label>
      <input type="text" placeholder="Alamat Pengurus" name="alamat-pengurus" required>
      <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>

      <div class="clearfix">
        <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
        <button type="submit" class="signupbtn">Submit</button>
      </div>
    </div>
  </form>


  <script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>

</body>
</html>