basdat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

import register_user.urls as register_user
import login.urls as login
import register_organisasi.urls as register_organisasi

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^daftar/', include(register_user, namespace='daftar')),
    url(r'^masuk/', include(login, namespace='masuk')),
    url(r'^register-organisasi/', include(register_organisasi, namespace='register-organisasi')),
    url(r'^', RedirectView.as_view(url='/masuk/', permanent='true'), name='index')
]

login/urls.py
from django.conf.urls import url
from .views import index, login

urlpatterns = [
    url(r"^", index, name="index"),
    url(r"^submit/", login, name="submit")
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from __future__ import unicode_literals

from django.db import connection
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

def index(request):
    if 'username' in request.session.keys():
        return HttpResponseRedirect(reverse('profile:index'))
    html = 'layout/masuk.html'
    return render(request, html)

def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        with connection.cursor() as cursor:
            cursor.execute("SELECT email, password FROM sion.user WHERE email = %s AND password = %s", [username, password])
            exist = cursor.fetchone()

        if exist:
            request.session['username'] = username

            with connection.cursor() as cursor:
                cursor.execute("SELECT email FROM relawan WHERE email = %s", [username])
                exist = cursor.fetchone()

                if exist:
                    request.session['role'] = 'relawan'

            with connection.cursor() as cursor:
                cursor.execute("SELECT email FROM donatur WHERE email = %s", [username])
                exist = cursor.fetchone()

                if exist:
                    request.session['role'] = 'donatur'

            with connection.cursor() as cursor:
                cursor.execute("SELECT email FROM sponsor WHERE email = %s", [username])
                exist = cursor.fetchone()

                if exist:
                    request.session['role'] = 'sponsor'
        else:
            messages.error(request, "Username atau Password salah!")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

login/templates/layout/masuk.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <style>
		body {
			margin-top: 70px;
		}

		p {
			text-align: justify;
		}

		a {
			padding-top: 50px;
			text-decoration: underline;
		}

		#login {
			height: 250px;
			-webkit-box-shadow: 0px 2px 22px 0px rgba(0,0,0,0.2);
			-moz-box-shadow: 0px 2px 22px 0px rgba(0,0,0,0.2);
			box-shadow: 0px 2px 22px 0px rgba(0,0,0,0.2);
            padding: 15px;
        	border-radius: 10px;
		}
	</style>

	<title>Sistem Informasi Organisasi Nirlaba</title>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-xs-12">
				<h1>SION</h1>
				<h2>Sistem Informasi Organisasi Nirlaba</h2>
				<p>SION merupakan sistem informasi untuk pendaftaran organisasi nirlaba yang dikelola oleh masyarakat sekaligus sebagai media bagi organisasi untuk mengampanyekan kegiatan-kegiatannya.</p>
				<p>Sistem Informasi Organisasi Nirlaba (SION) memberi kesempatan untuk semua organisasi nirlaba untuk bergabung. Dengan bergabung kedalam sistem, membuat produktivitas menjadi lebih baik dari sebelumnya dengan berbagai macam fitur-fitur yang disediakan.</p>
				<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum viverra ultrices tincidunt. Mauris porttitor mauris et mauris tempor, eget accumsan libero ullamcorper. Maecenas odio nibh, tempus in nulla non, ultricies condimentum nisi. Nullam et turpis vitae lorem pellentesque ultrices. Etiam nec nunc ante. Phasellus a urna in libero faucibus fermentum sed suscipit lorem. Fusce venenatis varius condimentum. Aenean sapien felis, suscipit sit amet cursus ut, consectetur id eros. Sed pellentesque quam leo, at facilisis purus cursus hendrerit. Aliquam erat volutpat.</p>
				<p>Duis egestas ligula suscipit mi malesuada volutpat. Sed a libero urna. Sed eget auctor dui. Aliquam hendrerit libero lectus, eget rhoncus dui viverra eget. Nulla condimentum lectus neque, quis lacinia nibh tempus in. Duis rutrum, felis sit amet blandit condimentum, turpis turpis ullamcorper dui, nec ornare urna nisl eget massa. Sed facilisis, tortor sit amet porttitor porttitor, arcu leo viverra sem, quis dapibus velit elit nec eros. Aenean vestibulum odio ac accumsan consectetur.</p>
			</div>
			<div class="col-md-4 col-xs-12">
				<div id="login">
					<form action="{% url 'masuk:submit' %}" method="POST">
                        {% csrf_token %}
					  <div class="form-group">
					    <label for="inputUsername">Username</label>
					    <input name="username" type="text" class="form-control" id="inputUsername" placeholder="Username" required>
					  </div>
					  <div class="form-group">
					    <label for="inputPassword">Password</label>
					    <input name="password" type="password" class="form-control" id="inputPassword" placeholder="Password" required>
					  </div>
					  <button type="submit" class="btn btn-outline-primary float-right">Masuk</button>
					</form>
					<a href="{% url 'daftar:index' %}">Mendaftar</a>

                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ message }}
                    </div>
                    {% endfor %}

				</div>
			</div>
		</div>
	</div>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>