basdat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

import register_user.urls as register_user
import login.urls as login
import register_organisasi.urls as register_organisasi

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^daftar/', include(register_user, namespace='daftar')),
    url(r'^masuk/', include(login, namespace='masuk')),
    url(r'^register-organisasi/', include(register_organisasi, namespace='register-organisasi')),
    url(r'^', RedirectView.as_view(url='/masuk/', permanent='true'), name='index')
]

login/urls.py
from django.conf.urls import url
from .views import index, login

urlpatterns = [
    url(r"^", index, name="index"),
    url(r"^submit/", login, name="submit")
]

register_user/urls.py
from django.conf.urls import url
from .views import index, submit_form

urlpatterns = [
    url(r"^", index, name="index"),
    url(r"^submit", submit_form, name="submit_form")
]

register_user/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class User(models.Model):
    email = models.CharField(primary_key=True, max_length=50)
    password = models.CharField(max_length=50)
    nama = models.CharField(max_length=100)
    alamat_lengkap = models.TextField()

    class Meta:
        db_table = 'user'

class Sponsor(models.Model):
    email = models.ForeignKey('User', models.CASCADE, db_column='email', primary_key=True)
    logo_sponsor = models.ImageField()

    class Meta:
        db_table = 'sponsor'

class Donatur(models.Model):
    email = models.ForeignKey('User', models.CASCADE, db_column='email', primary_key=True)
    saldo = models.IntegerField(default=0)

    class Meta:
        db_table = 'donatur'

class Relawan(models.Model):
    email = models.ForeignKey('User', models.CASCADE, db_column='email', primary_key=True)
    no_hp = models.CharField(max_length=20)
    tanggal_lahir = models.DateField()

    class Meta:
        db_table = 'relawan'

class KeahlianRelawan(models.Model):
    email = models.ForeignKey('Relawan', models.CASCADE, db_column='email', primary_key=True)
    keahlian = models.CharField(max_length=50)

    class Meta:
        db_table = 'keahlian_relawan'
        unique_together = (('email', 'keahlian'),)

register_user/views.py
from __future__ import unicode_literals

from django.db import connection, IntegrityError
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

# Create your views here.
from django.views.decorators.csrf import csrf_exempt


def index(request):
    html = 'layout/daftar.html'
    return render(request, html)

def submit_form(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        nama = request.POST['name']
        alamat_lengkap = request.POST['jalan'] + ", " + request.POST['kecamatan'] + ", " + \
                         request.POST['kabupaten'] + ", " + request.POST['provinsi']

        try:
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO sion.user VALUES (%s, %s, %s, %s)", [email, password, nama, alamat_lengkap])
            print(request.POST['selectRole'])

            if request.POST['selectRole'] == 'relawan':
                no_hp = request.POST['no_hp']
                tgl_lahir = request.POST['tanggal_lahir']
                keahlian = request.POST['keahlian'].split(";")

                with connection.cursor() as cursor:
                    cursor.execute("INSERT INTO relawan VALUES (%s, %s, %s)", [email, no_hp, tgl_lahir])
                    for k in keahlian:
                        cursor.execute("INSERT INTO keahlian_relawan VALUES (%s, %s)", [email, k])

            elif request.POST['selectRole'] == 'sponsor':
                logo = request.POST['logo']

                with connection.cursor() as cursor:
                    cursor.execute("INSERT INTO sponsor VALUES (%s, %s)", [email, logo])

            elif request.POST['selectRole'] == 'donatur':
                with connection.cursor() as cursor:
                    cursor.execute("INSERT INTO donatur VALUES (%s)", [email])

            messages.success(request, "Akun anda berhasil dibuat, silahkan login!")
            return HttpResponseRedirect(reverse('masuk:index'))
        except IntegrityError:
            messages.error(request, "Email sudah terdaftar!")

    return HttpResponseRedirect(reverse('daftar:index'))

register_user/templates/layout/daftar.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <style>
		body {
			margin-top: 70px;
			margin-bottom: 70px;
		}

		hr {
			margin-bottom: 30px;
		}
		#formSection {
			width: 100%;
			height: 100%;
			-webkit-box-shadow: 0px 2px 22px 0px rgba(0,0,0,0.2);
			-moz-box-shadow: 0px 2px 22px 0px rgba(0,0,0,0.2);
			box-shadow: 0px 2px 22px 0px rgba(0,0,0,0.2);
            padding: 50px;
        	border-radius: 10px;
		}
	</style>

	<title>Mendaftar - Sistem Informasi Organisasi Nirlaba</title>
</head>
<body>
	<div class="container">
		<section id='formSection'>
			<h3>Form Pendaftaran User</h3>
			<hr/>
			<form id="form" action="{% url 'daftar:submit_form' %}" method="POST">
                {% csrf_token %}
				<div class="form-row" id='formDaftar'>
					<div class="form-group col-md-6">
						<label for="inputName">Nama</label>
						<input name="name" type="text" class="form-control" id="inputName" placeholder="Name" required>
					</div>
					<div class="form-group col-md-6">
						<label>Role</label>
						<select name="selectRole" id='selectRole' class="form-control">
			                <option value="relawan">Relawan</option>
			                <option value="sponsor">Sponsor</option>
			                <option value="donatur">Donatur</option>
			            </select>
					</div>
					<div class="form-group col-md-6">
						<label for="inputEmail">Email</label>
						<input name="email" type="email" class="form-control" id="inputEmail" placeholder="Email" required>
					</div>
					<div class="form-group col-md-6">
						<label for="inputPassword">Password</label>
						<input name="password" type="password" class="form-control" id="inputPassword" placeholder="Password" required>
					</div>
					<div class="form-group col-md-6">
						<label for="inputKecamatan">Kecamatan</label>
						<input name="kecamatan" type="text" class="form-control" id="inputKecamatan" placeholder="Kecamatan" required>
					</div>
					<div class="form-group col-md-6">
						<label for="inputKabupaten">Kabupaten</label>
						<input name="kabupaten" type="text" class="form-control" id="inputKabupaten" placeholder="Kabupaten" required>
					</div>
					<div class="form-group col-md-6">
						<label for="inputProvinsi">Provinsi</label>
						<input name="provinsi" type="text" class="form-control" id="inputProvinsi" placeholder="Provinsi" required>
					</div>
					<div class="form-group col-md-6">
						<label for="inputKodePos">Kode Pos</label>
						<input name="kode_pos" type="text" class="form-control" id="inputKodePos" placeholder="Kode Pos" required>
					</div>
					<div class="form-group col-md-12">
						<label for="inputJalan">Jalan/Desa/Kelurahan/No.Rumah</label>
						<input name="jalan" type="text" class="form-control" id="inputJalan" placeholder="Jalan/Desa/Kelurahan/No.Rumah" required>
					</div>
					<div class="form-group col-md-6">
						<label for='inputTanggal'>Tanggal Lahir</label>
						<input name="tanggal" id='inputTanggal' type='date' class='form-control' required>
					</div>
					<div class='form-group col-md-6'>
						<label for='inputNoHp'>Nomor Handphone</label>
						<input name="no_hp" id='inputNoHp' type='text' class='form-control' required>
					</div>
					<div class='form-group col-md-12'>
						<label for='isianKeahlian'>Keahlian</label>
						<input name="keahlian" id='isianKeahlian' type='text' class='form-control' required>
					</div>
				</div>

                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
                {% endfor %}

				<button type="submit" class="btn btn-outline-primary float-right">Submit</button>
			</form>
		</section>
	</div>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

	<script>
		$(document).ready(function () {
			$('#selectRole').change(function () {
				var selected = $('#selectRole').val();
	            if (selected === 'relawan') {
	            	$('#formDaftar div:gt(8)').remove();
	                $('#formDaftar').append("<div class='form-group col-md-6'><label for='inputTanggal'>Tanggal Lahir</label> \
	                        <input name='tanggal' id='inputTanggal' type='date' class='form-control' required></div> \
	                        <div class='form-group col-md-6'><label for='inputNoHp'>Nomor Handphone</label> \
	                        <input name='no_hp' id='inputNoHp' type='text' class='form-control' required></div> \
	                        <div class='form-group col-md-12'><label for='isianKeahlian'>Keahlian</label> \
	                        <input name='keahlian' id='isianKeahlian' type='text' class='form-control required'></div>")
	            }
	            else if (selected === 'sponsor') {
	            	$('#formDaftar div:gt(8)').remove();
	                $('#formDaftar').append("<div class='form-group col-md-4'><label for='inputLogo'>Logo</label> \
	                        <input name='logo' id='inputLogo' type='file' class='form-control' required></div>")
	            }
	            else {
	            	$('#formDaftar div:gt(8)').remove();
	            }
			});
		});
	</script>
</body>
</html>